<?php

/**
 * Implements hook_block_info().
 */
function recent_events_block_info() {
  $blocks['recent_events'] = [
    'info' => t('Recent events'),
    'cache' => DRUPAL_NO_CACHE,
  ];
  return $blocks;
}

/**
 * Implements hook_block_view().
 * @param string $delta
 * @return array
 */
function recent_events_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'recent_events' :
      $results = '';
      $now = time();

      $nids = db_select('node', 'n')
        ->fields('n', ['nid'])
        ->condition('n.type', 'event')
        ->condition('status', 1)
        ->orderBy('created', 'DESC')
        ->execute()
        ->fetchCol();

      $nodes = node_load_multiple($nids);
      $i = 0;

      foreach ($nodes as $nid => $node) {
        if ($now > $nodes[$nid]->field_event_date['und']['0']['value']) {
          $event_date = date("d-m-Y", $nodes[$nid]->field_event_date['und']['0']['value']);
          $results .= l(check_plain($node->title), 'node/' . $node->nid) . ' / ' . $event_date . "<br>";
          if (++$i == 5) {
            break;
          }
        }
      }

      $block['subject'] = 'Recent events';
      $block['content'] = $results;
      break;
    default:
      break;
  }

  return $block;
}
